[build]
  functions = "functions"  # Папка с функциями

[[redirects]]
  from = "/*"             # Все запросы
  to = "/.netlify/functions/retell"  # К функции retell
  status = 200            # Статус ответа
  force = true            # Принудительно перенаправлять
